# Generated by Django 4.0.7 on 2022-10-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assayCode', models.CharField(max_length=25)),
                ('batchDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
