# Generated by Django 4.0.7 on 2022-10-04 10:33

import base.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='isBatchProccessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='miscFields',
            field=models.JSONField(default='misc columns'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='numberOfSamples',
            field=models.PositiveSmallIntegerField(default=0, validators=[base.models.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batchDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
