# Generated by Django 4.0.7 on 2022-10-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_batch_isbatchproccessed_batch_miscfields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='batch',
            name='miscFields',
        ),
        migrations.AddField(
            model_name='batch',
            name='labels',
            field=models.ManyToManyField(to='base.batchlabel'),
        ),
    ]
