# Generated by Django 4.0.7 on 2022-10-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_batchlabel_remove_batch_miscfields_batch_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='labels',
        ),
        migrations.AddField(
            model_name='batch',
            name='miscFields',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='BatchLabel',
        ),
    ]
