# Generated by Django 4.0.7 on 2022-10-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_batch_miscfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='batch',
            name='miscFields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
