# Generated by Django 4.0.7 on 2022-10-04 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_assay_alter_batch_miscfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='assayCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.assay'),
        ),
    ]
