# Generated by Django 4.0.7 on 2022-10-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_batch_assaycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='assayCode',
        ),
    ]
