# Generated by Django 4.0.7 on 2022-10-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_batch_assaycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='assayCode',
            field=models.CharField(default='hu', max_length=25),
            preserve_default=False,
        ),
    ]
