# Generated by Django 4.0.7 on 2022-10-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_batch_assaycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='code',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='assay',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='assayCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.assay'),
        ),
    ]
