# Generated by Django 4.0.7 on 2022-10-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0015_groupassay_assays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='assayCode',
        ),
        migrations.AddField(
            model_name='assay',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='assay',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='batch',
            name='object_id',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='groupassay',
            name='assays',
        ),
        migrations.AddField(
            model_name='groupassay',
            name='assays',
            field=models.ManyToManyField(null=True, to='base.assay'),
        ),
    ]
