# Generated by Django 4.0.7 on 2022-10-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_assay_content_type_remove_assay_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='singleAssay',
        ),
        migrations.RemoveField(
            model_name='groupassay',
            name='assays',
        ),
        migrations.AddField(
            model_name='groupassay',
            name='groupAssays',
            field=models.ManyToManyField(to='base.assay'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='groupAssay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.groupassay'),
        ),
    ]
