# Generated by Django 4.0.7 on 2022-10-04 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_batch_singleassay_remove_groupassay_assays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='groupAssays',
            field=models.ManyToManyField(to='base.assay'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='groupAssay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.assay'),
        ),
        migrations.DeleteModel(
            name='GroupAssay',
        ),
    ]
