# Generated by Django 4.0.7 on 2022-10-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_assay_groupassays_alter_batch_groupassay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='assay',
            name='groupAssays',
            field=models.ManyToManyField(blank=True, to='base.assay'),
        ),
    ]
