# Generated by Django 4.0.7 on 2022-10-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_groupassays_assay_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='code',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
