# Generated by Django 4.0.7 on 2022-10-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_assay_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='groupAssay',
            new_name='assay',
        ),
    ]
