# Generated by Django 4.0.7 on 2022-10-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_batch_miscfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='assay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.assay'),
        ),
    ]
