# Generated by Django 4.0.7 on 2022-10-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_batch_assay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='group',
            field=models.ManyToManyField(blank=True, default='null', to='base.assay'),
        ),
    ]
