# Generated by Django 4.0.7 on 2022-10-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_assay_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='code',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assay',
            name='name',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
