# Generated by Django 4.0.7 on 2022-10-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_assay_code_alter_assay_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
