# Generated by Django 4.0.7 on 2022-10-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_assay_reagents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='reagents',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='miscFields',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
