# Generated by Django 4.0.7 on 2022-10-06 15:55

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_assay_reagents_alter_batch_miscfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='reagents',
            field=models.JSONField(blank=True, default=base.models.get_default_reagents, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='miscFields',
            field=models.JSONField(blank=True, default=base.models.get_default_miscFields, null=True),
        ),
    ]
