# Generated by Django 4.0.7 on 2022-10-06 23:49

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_assay_reagent_assay_reagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='units',
            field=models.CharField(default='units', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supply',
            name='units',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[base.models.validate_quantity]),
        ),
        migrations.AlterField(
            model_name='supply',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[base.models.validate_quantity]),
        ),
    ]
