# Generated by Django 4.0.7 on 2022-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_reagent_units_supply_units_alter_reagent_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='reagent',
            field=models.ManyToManyField(blank=True, default='null', to='base.reagent'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='supply',
            field=models.ManyToManyField(blank=True, default='null', to='base.supply'),
        ),
    ]
