# Generated by Django 4.0.7 on 2022-10-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_assay_reagent_alter_assay_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='units',
            field=models.CharField(choices=[('Liters', 'L'), ('Milliliters', 'mL'), ('Microliters', 'µL'), ('Grams', 'g'), ('Milligrams', 'mg')], default='Liters', max_length=15),
        ),
        migrations.AlterField(
            model_name='supply',
            name='units',
            field=models.CharField(choices=[('Liters', 'L'), ('Milliliters', 'mL'), ('Microliters', 'µL'), ('Grams', 'g'), ('Milligrams', 'mg')], default='Liters', max_length=15),
        ),
    ]
