# Generated by Django 4.0.7 on 2022-10-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_reagent_units_alter_supply_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='miscFields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
