# Generated by Django 4.0.7 on 2022-10-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_batch_miscfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='reagent',
            field=models.ManyToManyField(blank=True, to='base.reagent'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='supply',
            field=models.ManyToManyField(blank=True, to='base.supply'),
        ),
    ]
