# Generated by Django 4.0.7 on 2022-10-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_assay_reagent_alter_assay_supply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='miscFields',
            new_name='fieldLabels',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='assay',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batchDate',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='isBatchProccessed',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='numberOfSamples',
        ),
    ]
