# Generated by Django 4.0.7 on 2022-10-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='fieldLabels',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
