# Generated by Django 4.0.7 on 2022-10-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_batch_fieldlabels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='fieldLabels',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
