# Generated by Django 4.0.7 on 2022-10-17 20:15

import base.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_batch_fieldlabels'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='assay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.assay'),
        ),
        migrations.AddField(
            model_name='batch',
            name='batchDate',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='batch',
            name='isBatchProcessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='numberOfSamples',
            field=models.PositiveSmallIntegerField(default=0, validators=[base.models.validate_nonzero]),
        ),
    ]
