# Generated by Django 4.0.7 on 2022-10-17 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_batch_assay_batch_batchdate_batch_isbatchprocessed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='assayName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assay_name', to='base.assay'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='assay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assay_code', to='base.assay'),
        ),
    ]
