# Generated by Django 4.0.7 on 2022-10-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_assay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='catalogNumber',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='catalogNumber',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
