# Generated by Django 4.0.7 on 2022-10-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_alter_reagent_catalognumber_alter_reagent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='dna_extraction',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='rna_extraction',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
