# Generated by Django 4.0.7 on 2022-10-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_batch_dna_extraction_batch_rna_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='supply',
            field=models.ManyToManyField(blank=True, to='base.supply'),
        ),
    ]
