# Generated by Django 4.0.7 on 2022-10-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_assay_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_group', models.CharField(max_length=4)),
            ],
        ),
    ]
