# Generated by Django 4.0.7 on 2022-10-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_batch_extraction_groups'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batch',
            name='extraction_groups',
        ),
    ]
