# Generated by Django 4.0.7 on 2022-10-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_remove_batch_extraction_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='dna_extraction',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='rna_extraction',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
