# Generated by Django 4.0.7 on 2022-10-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_batch_dna_extraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='dna_extraction',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='rna_extraction',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
