# Generated by Django 4.0.7 on 2022-11-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_batch_dna_extraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='reagent',
            field=models.ManyToManyField(blank=True, null=True, to='base.reagent'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='supply',
            field=models.ManyToManyField(blank=True, null=True, to='base.supply'),
        ),
    ]
