# Generated by Django 4.0.7 on 2022-11-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_rename_group_assay_assays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='assays',
            field=models.ManyToManyField(blank=True, default='null', related_name='assays+', to='base.assay'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='reagent',
            field=models.ManyToManyField(blank=True, related_name='reagent+', to='base.reagent'),
        ),
        migrations.AlterField(
            model_name='assay',
            name='supply',
            field=models.ManyToManyField(blank=True, related_name='supply+', to='base.supply'),
        ),
    ]
