# Generated by Django 4.0.7 on 2022-11-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_assay_assays_alter_assay_reagent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='type',
            field=models.CharField(choices=[{'null', None}, ('DNA', 'DNA'), ('RNA', 'RNA'), ('Total nucleic', 'Total nucleic')], default=None, max_length=15),
        ),
    ]
