# Generated by Django 4.0.7 on 2022-11-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_alter_assay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('Total nucleic', 'Total nucleic'), ('NONE', 'NONE')], default='NONE', max_length=15),
        ),
    ]
