# Generated by Django 4.0.7 on 2022-11-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_alter_assay_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assay',
            old_name='assays',
            new_name='assay',
        ),
    ]
