# Generated by Django 4.0.7 on 2022-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_alter_assay_assay_alter_assay_reagent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batchDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
