# Generated by Django 4.0.7 on 2022-11-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_alter_batch_batchdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batchDate',
            field=models.DateField(default='2022-11-14 10:50'),
        ),
    ]
