# Generated by Django 4.0.7 on 2022-11-15 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_alter_batch_batchdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batchDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 15, 13, 45, 26, 857921)),
        ),
    ]
