# Generated by Django 4.0.7 on 2022-11-17 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_alter_batch_batchdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batchDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 17, 17, 32, 35, 88536)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='dna_extraction',
            field=models.CharField(blank=True, error_messages={'unique': 'Batch with this extraction group already exists'}, max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='rna_extraction',
            field=models.CharField(blank=True, error_messages={'unique': 'Batch with this extraction group already exists'}, max_length=3, null=True, unique=True),
        ),
    ]
