# Generated by Django 4.0.7 on 2022-11-29 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_alter_batch_batchdate_alter_batch_dna_extraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batchDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 13, 21, 14, 753873)),
        ),
    ]
